
runtime: python39

runtime_config:
  document_root: web

handlers:
- url: /(.+\.(ico|txt|gif|jpg|png|css|js))$
  static_files: web/\1
  upload: web/(.+)

- url: /index.html
  static_files: web/index.html
  upload: web/index.html

- url: /about.html
  static_files: web/about.html
  upload: web/about.html

- url: /coming-soon.html
  static_files: web/coming-soon.html
  upload: web/coming-soon.html 
 
- url: /consulting.html
  static_files: web/consulting.html
  upload: web/consulting.html  

- url: /contact2.html
  static_files: web/contact2.html
  upload: web/contact2.html

- url: /core_areas.html
  static_files: web/core_areas.html
  upload: web/core_areas.html

- url: /instructor_augmentation.html
  static_files: web/instructor_augmentation.html
  upload: web/instructor_augmentation.html  

- url: /events.html
  static_files: web/events.html
  upload: web/events.html

- url: /process.html
  static_files: web/process.html
  upload: web/process.html
  
- url: /project-detail.html
  static_files: web/project-detail.html
  upload: web/project-detail.html
  
- url: /services.html
  static_files: web/services.html
  upload: web/services.html  

- url: /content_management.html
  static_files: web/content_management.html
  upload: web/content_management.html

- url: /team.html
  static_files: web/team.html
  upload: web/team.html  

- url: /trainers.html
  static_files: web/trainers.html
  upload: web/trainers.html  

- url: /why_us.html
  static_files: web/why_us.html
  upload: web/why_us.html  

- url: /work_with_us.html
  static_files: web/work_with_us.html
  upload: web/work_with_us.html 
  
- url: /fly_me_trainer.html
  static_files: web/fly_me_trainer.html
  upload: web/fly_me_trainer.html 
  
- url: /blog.html
  static_files: web/blog.html
  upload: web/blog.html   

- url: /topics.html
  static_files: web/topics.html
  upload: web/topics.html 

- url: /brands.html
  static_files: web/brands.html
  upload: web/brands.html   

- url: /blog-detail.html
  static_files: web/blog-detail.html
  upload: web/blog-detail.html 

- url: /blog-detail4.html
  static_files: web/blog-detail4.html
  upload: web/blog-detail4.html 

- url: /blog-detail5.html
  static_files: web/blog-detail5.html
  upload: web/blog-detail5.html   

- url: /blog-detail6.html
  static_files: web/blog-detail6.html
  upload: web/blog-detail6.html   


- url: /contact-process.php
  script: web/contact-process.php

- url: /join_us.php
  script: web/join_us.php  

- url: /robots.txt
  static_files: web/robots.txt 
  upload: web/robots.txt

- url: /video
  static_dir: web/video

- url: /webfonts
  static_dir: web/webfonts
  
- url: /css
  static_dir: web/css
  
- url: /fonts
  static_dir: web/fonts
  
- url: /images
  static_dir: web/images
   
- url: /js
  static_dir: web/js

- url: /vendor
  static_dir: web/vendor

- url: /.*
  static_files: web/index.html
  upload: web/index.html

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

service_account: sincere-axon-308404@appspot.gserviceaccount.com
